# Custom Language File for Launcher Customizer

[ejs.app]
title = "Forgotten Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "https://x.com/DedsafioR"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/7qwJCqjX"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO DEDSAFIO T1"
welcomeDescription = "Minecraft Hardcore"
welcomeDescCTA = "You are just a few clicks away from DEDSAFIO."
